export const NORMAL = 'NORMAL';
export const MULTIVARIANT = 'MULTIVARIANT';
export const DEPENDENT = 'DEPENDENT';
export const DEPENDENT_MULTIVARIANT = 'DEPENDENT_MULTIVARIANT';
export const VARIANT = 'VARIANT';
export const DEPENDENT_VARIANT = 'DEPENDENT_VARIANT';
